version: "3"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  backend:
    build: backend/
    env_file: backend/.env
    depends_on:
      - db
    ports:
        - 3000:3000
  
  frontend:
    build: frontend/
    depends_on:
      - backend
    ports:
      - 5173:5173
  

# volumes:
#   pgdata: